Algoritmo "semnome"

Var

nome, resp : caracter
cont : inteiro

Inicio

      cont <-1
      resp <- "S"

      escreval ("Informe seu nome: ")
      leia (nome)

      enquanto resp = "S" faca
               escreval ("Seu nome é: ", nome)

               escreval ("Deseja continuar (S/N)?")
               leia (resp)
      fimenquanto


//    enquanto cont <= 10 faca
//             escreval ("Seu nome é: ", nome)
//             cont <- cont + 1
//

Fimalgoritmo